# Generated by Django 5.2.18 on 2026-10-09 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Gasto")], max_length=10
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
            ],
            options={
                "ordering": ["type", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "slug"), name="category_household_slug"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("type__in", ["income", "expense"])),
                        name="category_valid_type",
                    ),
                ],
            },
        ),
    ]
