# Generated by Django 5.2.18 on 2026-10-09 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("bank", "Banco"),
                            ("wallet", "Billetera virtual"),
                            ("other", "Otra cuenta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="ARS", max_length=3)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["household", "is_active"], name="wallets_fin_househo_ccdbaf_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("currency", "ARS")), name="account_ars_only"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["cash", "bank", "wallet", "other"])),
                        name="account_valid_kind",
                    ),
                ],
            },
        ),
    ]
