# Generated by Django 5.2.18 on 2026-10-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("households", "0001_initial"),
        ("transactions", "0001_initial"),
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="wallets.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transfers",
                to="wallets.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="households.household"
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="wallets.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="households.household"
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="transactions.financialtransaction",
            ),
        ),
        migrations.AddField(
            model_name="writereceipt",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="writereceipt",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="households.household"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["household", "effective_date", "id"], name="transaction_househo_f49a7e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="operation_positive_amount"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "ARS")), name="operation_ars_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["posted", "voided"])),
                name="operation_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="operation_positive_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category__isnull", False),
                        ("destination__isnull", True),
                        ("type__in", ["income", "expense"]),
                    ),
                    models.Q(
                        ("category__isnull", True),
                        ("destination__isnull", True),
                        ("type", "opening"),
                    ),
                    models.Q(
                        ("category__isnull", True),
                        ("destination__isnull", False),
                        ("type", "transfer"),
                        models.Q(("account", models.F("destination")), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="operation_valid_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["household", "account"], name="transaction_househo_301ee7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                fields=("transaction", "revision", "account"), name="ledger_revision_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True), name="ledger_nonzero"
            ),
        ),
        migrations.AddConstraint(
            model_name="writereceipt",
            constraint=models.UniqueConstraint(
                fields=("household", "actor", "key"), name="financial_write_key"
            ),
        ),
    ]
